//
// Generated file, do not edit! Created by nedtool 4.6 from PL_PKT.msg.
//

#ifndef _PL_PKT_M_H_
#define _PL_PKT_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PL_PKT.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet PL_PKT
 * {
 *     int id;
 *     int type;
 * }
 * </pre>
 */
class PL_PKT : public ::cPacket
{
  protected:
    int id_var;
    int type_var;

  private:
    void copy(const PL_PKT& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PL_PKT&);

  public:
    PL_PKT(const char *name=NULL, int kind=0);
    PL_PKT(const PL_PKT& other);
    virtual ~PL_PKT();
    PL_PKT& operator=(const PL_PKT& other);
    virtual PL_PKT *dup() const {return new PL_PKT(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doPacking(cCommBuffer *b, PL_PKT& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, PL_PKT& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PL_PKT_M_H_

