//
// Generated file, do not edit! Created by nedtool 4.6 from dlpdu.msg.
//

#ifndef _DLPDU_M_H_
#define _DLPDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>dlpdu.msg:16</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet DL_PDU
 * {
 *     int id;
 *     int type;
 *     int sadd;
 *     int dadd;
 * }
 * </pre>
 */
class DL_PDU : public ::cPacket
{
  protected:
    int id_var;
    int type_var;
    int sadd_var;
    int dadd_var;

  private:
    void copy(const DL_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DL_PDU&);

  public:
    DL_PDU(const char *name=NULL, int kind=0);
    DL_PDU(const DL_PDU& other);
    virtual ~DL_PDU();
    DL_PDU& operator=(const DL_PDU& other);
    virtual DL_PDU *dup() const {return new DL_PDU(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getSadd() const;
    virtual void setSadd(int sadd);
    virtual int getDadd() const;
    virtual void setDadd(int dadd);
};

inline void doPacking(cCommBuffer *b, DL_PDU& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DL_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DLPDU_M_H_

