//
// Generated file, do not edit! Created by nedtool 4.6 from N_PDU.msg.
//

#ifndef _N_PDU_M_H_
#define _N_PDU_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>N_PDU.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet N_PDU
 * {
 *     int src;
 *     int dest;
 *     char type;
 * }
 * </pre>
 */
class N_PDU : public ::cPacket
{
  protected:
    int src_var;
    int dest_var;
    char type_var;

  private:
    void copy(const N_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const N_PDU&);

  public:
    N_PDU(const char *name=NULL, int kind=0);
    N_PDU(const N_PDU& other);
    virtual ~N_PDU();
    N_PDU& operator=(const N_PDU& other);
    virtual N_PDU *dup() const {return new N_PDU(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getDest() const;
    virtual void setDest(int dest);
    virtual char getType() const;
    virtual void setType(char type);
};

inline void doPacking(cCommBuffer *b, N_PDU& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, N_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef _N_PDU_M_H_

