//
// Generated file, do not edit! Created by nedtool 4.6 from packet.msg.
//

#ifndef _PACKET_M_H_
#define _PACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // This program is free software: you can redistribute it and/or modify
 * // it under the terms of the GNU Lesser General Public License as published by
 * // the Free Software Foundation, either version 3 of the License, or
 * // (at your option) any later version.
 * // 
 * // This program is distributed in the hope that it will be useful,
 * // but WITHOUT ANY WARRANTY; without even the implied warranty of
 * // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * // GNU Lesser General Public License for more details.
 * // 
 * // You should have received a copy of the GNU Lesser General Public License
 * // along with this program.  If not, see http://www.gnu.org/licenses/.
 * //
 * packet mypkt
 * {
 *     int id;
 *     int type;
 *     int sadd;
 *     int dadd;
 * }
 * </pre>
 */
class mypkt : public ::cPacket
{
  protected:
    int id_var;
    int type_var;
    int sadd_var;
    int dadd_var;

  private:
    void copy(const mypkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const mypkt&);

  public:
    mypkt(const char *name=NULL, int kind=0);
    mypkt(const mypkt& other);
    virtual ~mypkt();
    mypkt& operator=(const mypkt& other);
    virtual mypkt *dup() const {return new mypkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getSadd() const;
    virtual void setSadd(int sadd);
    virtual int getDadd() const;
    virtual void setDadd(int dadd);
};

inline void doPacking(cCommBuffer *b, mypkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, mypkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _PACKET_M_H_

